# Generated by Django 4.0.3 on 2022-04-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_name', models.CharField(max_length=200)),
                ('top_dec', models.TextField()),
                ('top_image', models.ImageField(default='', upload_to='vms/images')),
                ('top_btn', models.IntegerField()),
            ],
        ),
    ]
