# Generated by Django 4.0.3 on 2022-04-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmsproject', '0003_abouttext_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
