# Generated by Django 4.0.3 on 2022-04-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsproject', '0004_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttext',
            name='about_img',
            field=models.ImageField(default='', upload_to='vmsproject/images'),
        ),
        migrations.AddField(
            model_name='abouttext',
            name='about_img2',
            field=models.ImageField(default='', upload_to='vmsproject/images'),
        ),
        migrations.AddField(
            model_name='abouttext',
            name='about_para1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='abouttext',
            name='about_para2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='abouttext',
            name='about_para3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='abouttext',
            name='about_para4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='abouttext',
            name='about_subtitle1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='abouttext',
            name='about_subtitle2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='abouttext',
            name='about_subtitle3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='abouttext',
            name='about_years',
            field=models.CharField(default='', max_length=50),
        ),
    ]
