# Generated by Django 4.0.3 on 2022-04-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsproject', '0005_abouttext_about_img_abouttext_about_img2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abouttext',
            old_name='about_img',
            new_name='about_img1',
        ),
        migrations.AddField(
            model_name='abouttext',
            name='about_img3',
            field=models.ImageField(default='', upload_to='vmsproject/images'),
        ),
        migrations.AddField(
            model_name='abouttext',
            name='about_img4',
            field=models.ImageField(default='', upload_to='vmsproject/images'),
        ),
        migrations.AddField(
            model_name='abouttext',
            name='about_img5',
            field=models.ImageField(default='', upload_to='vmsproject/images'),
        ),
        migrations.AddField(
            model_name='abouttext',
            name='about_img6',
            field=models.ImageField(default='', upload_to='vmsproject/images'),
        ),
        migrations.AddField(
            model_name='abouttext',
            name='about_img7',
            field=models.ImageField(default='', upload_to='vmsproject/images'),
        ),
        migrations.AddField(
            model_name='abouttext',
            name='about_img8',
            field=models.ImageField(default='', upload_to='vmsproject/images'),
        ),
    ]
