# Generated by Django 4.0.3 on 2022-04-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmsproject', '0006_rename_about_img_abouttext_about_img1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abouttext',
            name='about_img5',
        ),
        migrations.RemoveField(
            model_name='abouttext',
            name='about_img6',
        ),
        migrations.RemoveField(
            model_name='abouttext',
            name='about_img7',
        ),
        migrations.RemoveField(
            model_name='abouttext',
            name='about_img8',
        ),
    ]
