# Generated by Django 4.0.3 on 2022-04-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsproject', '0008_alter_abouttext_about_img1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttext',
            name='about_img1',
            field=models.ImageField(default='', upload_to='vmsproject/images'),
        ),
        migrations.AlterField(
            model_name='abouttext',
            name='about_img2',
            field=models.ImageField(default='', upload_to='vmsproject/images'),
        ),
        migrations.AlterField(
            model_name='abouttext',
            name='about_img3',
            field=models.ImageField(default='', upload_to='vmsproject/images'),
        ),
        migrations.AlterField(
            model_name='abouttext',
            name='about_img4',
            field=models.ImageField(default='', upload_to='vmsproject/images'),
        ),
    ]
