# Generated by Django 4.0.3 on 2022-04-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsproject', '0011_alter_product_product_dec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_dec',
            field=models.TextField(default=''),
        ),
    ]
