# Generated by Django 4.0.3 on 2022-04-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsproject', '0012_alter_product_product_dec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibition_image', models.ImageField(default='', upload_to='vmsproject/images')),
            ],
        ),
    ]
