# Generated by Django 4.0.3 on 2022-04-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsproject', '0014_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dec', models.TextField(default='')),
                ('designation', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='vmsproject/images')),
            ],
        ),
    ]
