# Generated by Django 4.0.3 on 2022-04-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsproject', '0016_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('dec', models.TextField(default='')),
                ('image1', models.ImageField(default='', upload_to='vmsproject/images')),
                ('imag2', models.ImageField(default='', upload_to='vmsproject/images')),
            ],
        ),
    ]
