# Generated by Django 4.0.3 on 2022-04-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsproject', '0017_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=600),
        ),
    ]
