# Generated by Django 4.0.3 on 2022-04-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmsproject', '0018_alter_services_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='imag2',
            new_name='image2',
        ),
    ]
