# Generated by Django 4.0.3 on 2022-04-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsproject', '0019_rename_imag2_services_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='social_icons',
            field=models.BooleanField(default=False),
        ),
    ]
