# Generated by Django 4.0.3 on 2022-05-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsproject', '0022_contact_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_icons', models.BooleanField(default=False)),
                ('info', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('num1', models.CharField(max_length=500)),
            ],
        ),
    ]
