# Generated by Django 4.0.3 on 2022-05-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmsproject', '0024_navigationbar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigationbar',
            old_name='navtitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='navigationbar',
            old_name='navurl',
            new_name='url',
        ),
    ]
