# Generated by Django 4.0.3 on 2022-05-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmsproject', '0026_thanks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thanks',
            name='Button_Url',
        ),
    ]
