# Generated by Django 4.0.3 on 2022-05-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsproject', '0027_remove_thanks_button_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationbar',
            name='pos',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
